### ISSUE TITLE
Bug: Want to add Validation in Category page using yup schema

### ISSUE THREAD

**Issue by realvishalrana** [michaelshimeles/cms#121]
![image](https://github.com/user-attachments/assets/ae4a6606-3012-4106-96d1-997b13b0454f)

api call without any validation

**Comment by michaelshimeles** [comment]
yeah need to comb through some of the apis and add zod schema... feel free to make a PR and I'll merge it...

**Comment by realvishalrana** [comment]
@michaelshimeles  Fix : unnecessary API call in on category page. review and merge this https://github.com/michaelshimeles/tsafi/pull/122 pull request
