### ISSUE TITLE
Unable to setup local environment, pls elaborate more on this in README.md

### ISSUE THREAD

**Issue by kapoorp99** [michaelshimeles/cms#47]

**Comment by michaelshimeles** [comment]
I need to update the db schema, give me a few hours and I'll push an update ser

**Comment by kapoorp99** [comment]
Sure @michaelshimeles , also i have a suggestion to add an onboarding flow for a new user, it will help new users to better undertand the product

**Comment by michaelshimeles** [comment]
I just updated the schema, should work now. Let me know if ur having any specific errors

**Comment by kapoorp99** [comment]
Yes i have seen, but can you pls elaborate more on setting up webhooks and env variables , it will be really helpful to all of us

**Comment by michaelshimeles** [comment]
It would help if you had more specific questions? :)

**Comment by kapoorp99** [comment]
Actually i am unable to generate API keys for platforms and services used other than clerk, so need help in that

**Comment by michaelshimeles** [comment]
Join my discord for help like that: https://discord.gg/SZZV74mCuV

**Comment by kapoorp99** [comment]
okk
