### ISSUE TITLE
[security bug] www subdomain is accepted

### ISSUE THREAD

**Issue by 6km** [michaelshimeles/cms#52]
Hi @michaelshimeles

I tried to set the subdomain to `www` to check if there's a bug with it, and it accepted it.
Now the main page https://www.tsafi.xyz/ redirects to my site.

Sorry for that, I really didn't mean to do it. Please fix this bug ASAP.

![image](https://github.com/michaelshimeles/tsafi/assets/62352949/b03ad2f7-07bc-4291-96bc-3848c6b8bacc)

**Comment by michaelshimeles** [comment]
I just pushed a fix, thanks for pointing this out

**Comment by 6km** [comment]
> I just pushed a fix, thanks for pointing this out

Thanks for fixing that! I was stuck on the home page.

**Comment by 6km** [comment]
@michaelshimeles I tried again and it still accepts it. By the way, I guess staging.tsafi.xyz should not be allowed too.

**Comment by michaelshimeles** [comment]
pushing a fix

**Comment by michaelshimeles** [comment]
try testing it out now @6km

**Comment by 6km** [comment]
Thanks @michaelshimeles! I tested it out and it has been fixed! 🚀
