### ISSUE TITLE
Where i have to add uploadthing API keys?

### ISSUE THREAD

**Issue by kapoorp99** [michaelshimeles/cms#56]
@michaelshimeles any overview on this? I am facing issue in setting up the project at my local environment

**Comment by iasadk** [comment]
If you specifically facing issue with uploadThing then just remember that you don't have to use UPLOAD THING variable explicity in your app. It will be used automatically.Like this:
UPLOADTHING_SECRET=VALUE
UPLOADTHING_APP_ID=VALUE

**Comment by kapoorp99** [comment]
Sorry, i didn't get, can you pls share how you have setup the database?

**Comment by iasadk** [comment]
Yeah sure it's pretty simple.
Go to supbase > login > create a new project [under your organisation] > get anon key and go to database under settings to get database url.
for some reason I also dont understand why @tsaifi had used DIRECT_URL as I had commented it in prisma file.

Then after pasting all credentials 
run:
```
npx prisma validate -> to validate your prisma schemas
```
```
npx prisma migrate dev --name init     -> to sync schema with supabase
```
That all work for me.
