### ISSUE TITLE
feature : Automatically Generate Slug from Blog Topic

### ISSUE THREAD

**Issue by imjishan** [michaelshimeles/cms#57]
**Description** :

I would like to request a feature that automatically generates a slug from the blog topic as we start typing in the textarea. This feature would be very useful for users to ensure consistent and SEO-friendly slugs without manually typing them out.Proposed Solution:As the user starts typing in the "Blog Topic" textarea, dynamically generate a slug in a separate "Slug" input field.The slug should be auto-updated as the user types or modifies the blog topic.Ensure the generated slug is URL-friendly (lowercase, hyphens instead of spaces, no special characters).

**Benefits** :

Saves time for users by automating slug generation.Ensures slugs are consistent and SEO-friendly.Reduces human error in manually creating slugs.

**Comment by michaelshimeles** [comment]
this is a great idea, will implement this unless someone wants to do it sooner :)

**Comment by michaelshimeles** [comment]
Added this. PR has been merged

[PR](https://github.com/michaelshimeles/tsafi/pull/58)
