### ISSUE TITLE
null value in column "author_id" of relation "author" violates not-null constraint

### ISSUE THREAD

**Issue by djclarkson** [michaelshimeles/cms#59]
I get these insert ID errors for add site and add author. 

```
Creating author with: { name: 'dave', instagram: '', twitter: '', image_url: '' }
User ID from auth: user_2hWUVia8ft434vL4VLj2M7Cy9AR
Inserting author into database
Error inserting data into Supabase: {
  code: '23502',
  details: 'Failing row contains (2, user_2hWUVia8ft434vL4VLj2M7Cy9AR, null, dave, , , ).',
  hint: null,
  message: 'null value in column "author_id" of relation "author" violates not-null constraint'
```

Don't see any code to create the side_id or the author_id, nor anything in the supabase setup to generate it. Logically seems like it should be a slug of the site name or author name. I added some code with slugify to handle it, but wondered if there was something I missed. 

```
 // Generate a slug for the author_id
  const author_id = slugify(name, { lower: true, strict: true });

```

**Comment by iasadk** [comment]
```
author_id 
```
firstly,
this is an auto-generated Id BTW you can see it in 'prisma schema' file or just search 'uuid()' function.

secondly, 
this error is showing because of some version issues I'm not able to figure it out once I do it I will mention it here my schema is also not able to generate this.

**Comment by michaelshimeles** [comment]
Thank you @iasadk! That's essemtially it!
